# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DissolveRelated
                                 A QGIS plugin
 This plugn allows to dissolve only connected objects
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-29
        copyright            : (C) 2021 by Piotr Andryk
        email                : andryk.p@wp.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DissolveRelated class from file DissolveRelated.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dissolve_related import DissolveRelated
    return DissolveRelated(iface)
