# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointOnArcIntersection
                                 A QGIS plugin
 The plugin creates a new layer with points on arcs' intersection within the same layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-24
        copyright            : (C) 2022 by Piotr Andryk
        email                : andryk.p@wp.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointOnArcIntersection class from file PointOnArcIntersection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_on_arc_intersection import PointOnArcIntersection
    return PointOnArcIntersection(iface)
